apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
    app: "consul"
    zone: "lab"
    version: "20190411_1"
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
        name: consul
    spec:
      serviceAccountName: consul
      containers:
        - name: shell
          image: "kirscht/wmconsul:latest"
          #volumeMounts:
          #  - mountPath: "/projected-volume"
          #    name: all-in-one
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          #command:
          #  - "/bin/sh"
          #  - "-ec"
          #  - env
          #  - |
          #      export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
          #      consul kv put hello world
          #ports:
          #  - containerPort: 22
          #    # hostPort: 2222
          #volumeMounts:
          #  - name: consul
          #    mountPath: /consul/data
      #volumes:
      #- name: all-in-one
      #  projected:
      #    sources:
      #      - secret:
      #          name: firstnode      #  - name: consul
      #    persistentVolumeClaim:
      #      claimName: consul

                  #expirationSeconds: 7200
                  #audience: vault

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: consul-example-deployment
# spec:
#   replicas: 1
#   selector:
#    matchLabels:
#      app: consul-example
#  template:
#    metadata:
#      labels:
#        app: consul-example
#    spec:
#      containers:
#        - name: example
#          image: "consul:latest"
#          env:
#            - name: HOST_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.hostIP
#          command:
#            - "/bin/sh"
#            - "-ec"
#            - |
#                export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
#                consul kv put hello world